plugins:
  student_verification_alert_enabled:
    default: true
    client: true
  student_verification_alert_visible_groups:
    default: "unverified_users|grace_period_users"
    type: list
    client: true
  student_verification_alert_message:
    default: "Verify before you start posting as student, please click <img src=\"https://raw.githubusercontent.com/ckchamara/discourse-student-verification-alert/e661d288bbfaf100d1badb27303db85317d128ef/assets/images/unverified-label.svg\" alt=\"verify\" width=\"71\" height=\"29\"> in the header."
    client: true
  student_verification_alert_background_color:
    default: "#e6f0ff"
    client: true
  student_verification_alert_border_color:
    default: "#b3d9ff"
    client: true
  student_verification_alert_text_color:
    default: "#0066cc"
    client: true
  student_verification_alert_close_button_color:
    default: "#0066cc"
    client: true
