plugins:
  student_verification_alert_enabled:
    default: true
    client: true
  student_verification_alert_visible_groups:
    default: "unverified_users|grace_period_users"
    type: list
    client: true
  student_verification_alert_message:
    default: "Verify before you start posting as student, please click <img src='/plugins/discourse-student-verification-alert/images/unverified-label.svg' alt='verify' style='display: inline; height: 16px; margin: 0 4px; vertical-align: middle;'> in the header."
    client: true
  student_verification_alert_background_color:
    default: "#e6f0ff"
    client: true
  student_verification_alert_border_color:
    default: "#b3d9ff"
    client: true
  student_verification_alert_text_color:
    default: "#0066cc"
    client: true
  student_verification_alert_close_button_color:
    default: "#0066cc"
    client: true
